### ISSUE TITLE
Sticky States on ng2

### ISSUE THREAD

**Issue by dcarabott** [ui-router/sticky-states#1]
I've been trying to use sticky states with ng2. The 'Sticky States' feature looks like it requires `ui-router-core`  >= 2.0.0. ng2 is currently on `ui-router-core` = 1.0.1. I could be missing something here, but does this mean that at this point in time its not possible to use 'Sticky States' with ng2 since it requires a more recent version of `ui-router-core` due to its 'plugin' functionality?

**Comment by christopherthielen** [comment]
I believe it does require ui-router-core 2.0.0+.

I'm actively working on the ng2 codebase updating it to ui-router-core 3.x.  I plan to release ui-router-ng2 beta.4 ASAP (I'm blocked on some AoT compile and lazy loading problems right now)

**Comment by christopherthielen** [comment]
Closing, since this should no longer be an issue.

For anyone finding this, I added [5 example sticky-states projects](https://github.com/ui-router/sticky-states/tree/master/examples):

- AngularJS + npm + webpack
- AngularJS + bower + script tags
- AngularJS + npm + script tags
- Angular CLI
- Create React App
