### ISSUE TITLE
UI-router uiOnParamsChanged event is not triggered when StickyStatesPlugin is enabled

### ISSUE THREAD

**Issue by nazar-kuzo** [ui-router/sticky-states#16]
@christopherthielen,

I use uiOnParamsChanged event for catching dynamic state parameter change, but when I enable StickyStatesPlugin it stop propagation. Spend some time drilling down issue and definitely lives under "_calculateStickyTreeChanges" method as a part of "_addCreateHook" hook.

Seems like this line `var shouldRewritePaths = ['entering', 'exiting'].some(function (path) { return !!simulatedTC[path].length; });` sais that it needs to overwrite path and in the same time reverts state params changes that supposed to trigger "uiOnParamsChanged" event in future.

Reproduced on:
"uirouter/core": "5.0.3",
"uirouter/angularjs": "1.0.3",
"uirouter/sticky-states": "1.4.1",

Please notice, this plugin will not work (application crashes, webpack build crashes) with upper version of "uirouter/core" or "uirouter/angularjs"

Thanks for your help!

**Comment by jnfeinstein** [comment]
I think I'm experiencing the same issue.  I have states that use `reloadOnSearch: false`.  The `onSuccess` transition event would be fired when a query param changed, even if the state didn't change.  With this plugin installed the event is no longer thrown.  This is actually critical since `ui-sref` depends on this hook to update, which means query param inheritance is broken.

**Comment by jnfeinstein** [comment]
@nazar-kuzo confirmed that I'm experiencing the same issue you are.  The line you pointed to is the culprit.

**Comment by christopherthielen** [comment]
@nazar-kuzo i merged a commit to `@uirouter/core` that should fix this in the next release of uirouter/angularjs.  

I'd like to understand the problem you had building this with webpack.  Can you elaborate (please create a new issue)
